language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

env:
  - CARGO_FEATURES=""
    REPORTING_CARGO_FEATURES=""
  - CARGO_FEATURES="memory_usage" 
    REPORTING_CARGO_FEATURES="memory_usage"
  - CARGO_FEATURES="serialization"
    REPORTING_CARGO_FEATURES=""

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - set -ex
  # We manually build/test each crate and pass in any necessary feature flags
  # to work around rust-lang/cargo#4942
  
  # codespan
  - cargo build --manifest-path=codespan/Cargo.toml --verbose --no-default-features --features="$CARGO_FEATURES"
  - cargo test --manifest-path=codespan/Cargo.toml --verbose --no-default-features --features="$CARGO_FEATURES"
  # codespan-lsp
  - cargo build --manifest-path=codespan-lsp/Cargo.toml --verbose
  - cargo test --manifest-path=codespan-lsp/Cargo.toml --verbose
  # codespan-reporting
  - cargo build --manifest-path=codespan-reporting/Cargo.toml --verbose --no-default-features --features="$REPORTING_CARGO_FEATURES"
  - cargo test --manifest-path=codespan-reporting/Cargo.toml --verbose --no-default-features --features="$REPORTING_CARGO_FEATURES"
