[package]
name = "codespan-reporting"
version = "0.1.2"
readme = "README.md"
license = "Apache-2.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "Diagnostic reporting support for the codespan crate"
homepage = "https://github.com/brendanzab/codespan"
repository = "https://github.com/brendanzab/codespan"
documentation = "https://docs.rs/codespan-reporting"
exclude = ["assets/**"]

[dependencies]
codespan = { path = "../codespan", version = "0.1.1" }
termcolor = "0.3.4"

[dev-dependencies]
structopt = "0.2.7"
