[package]
name = "codespan"
version = "0.1.2"
readme = "../README.md"
license = "Apache-2.0"
authors = ["Brendan Zabarauskas <bjzaba@yahoo.com.au>"]
description = "Data structures for tracking locations in source code"
homepage = "https://github.com/brendanzab/codespan"
repository = "https://github.com/brendanzab/codespan"
documentation = "https://docs.rs/codespan"

[dependencies]
failure = "0.1.1"
serde_derive = { version = "1", optional = true }
serde = { version = "1", optional = true }
itertools = "0.7"
heapsize = { version = "0.4", optional = true }
heapsize_derive = { version = "0.1", optional = true }

[dev-dependencies]
pretty_assertions = "0.5.0"

[features]
serialization = ["serde", "serde/rc", "serde_derive"]
memory_usage = ["heapsize_derive", "heapsize"]
